# Generated by Django 3.2.8 on 2021-11-17 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20211117_0943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlescope',
            old_name='scope',
            new_name='tag',
        ),
        migrations.AlterField(
            model_name='articlescope',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope', to='articles.article'),
        ),
    ]
